import fs from 'fs';
import path from 'path';

const filePath = path.resolve('src/routes/index.tsx');
let lines = fs.readFileSync(filePath, 'utf8').split('\n');

// 1. Add OurValuesSection import at top if needed
let topImportLine = lines.findIndex(l => l.includes("from '../components/home/HomeSections';"));
if (topImportLine !== -1 && !lines.some(l => l.includes("OurValuesSection"))) {
  lines.splice(topImportLine + 1, 0, "import { OurValuesSection } from '../components/ui/OurValuesGrid';");
}

// 2. Find start of HERO (line starting with /* ═══════ HERO ═══════ */)
// and start of SCROLL STORYTELLING
const heroLineIdx = lines.findIndex(l => l.includes("/* ═══════════════════ HERO ═══════════════════ */"));
const storyLineIdx = lines.findIndex(l => l.includes("/* ═══════════════════ SCROLL STORYTELLING ═══════════════════ */"));

console.log('heroLineIdx:', heroLineIdx, 'storyLineIdx:', storyLineIdx);

if (heroLineIdx !== -1 && storyLineIdx !== -1 && storyLineIdx > heroLineIdx) {
  const replacementLines = [
    '/* ═══════════════════ HERO ═══════════════════ */',
    '',
    'const HOME_BANNERS = [',
    '  "/ZOHO_CRM_Banner.png",',
    '  "/SAP_Implementation_Banner.png",',
    '  "/Threatcorp_Banner.png",',
    '  "/Manage_Engine_Banner.png",',
    '];',
    '',
    'function Hero() {',
    '  const [index, setIndex] = useState(0);',
    '  const [videoPhase, setVideoPhase] = useState(true);',
    '  const videoRef = useRef<HTMLVideoElement>(null);',
    '  const ref = useRef<HTMLElement>(null);',
    '  const { scrollYProgress } = useScroll({ target: ref, offset: ["start start", "end start"] });',
    '  const heroY = useTransform(scrollYProgress, [0, 1], [0, 120]);',
    '  const heroOpacity = useTransform(scrollYProgress, [0, 0.6, 1], [1, 1, 0]);',
    '',
    '  useEffect(() => {',
    '    if (videoPhase) return;',
    '    const t = setInterval(() => setIndex((i) => (i + 1) % HOME_BANNERS.length), 6000);',
    '    return () => clearInterval(t);',
    '  }, [videoPhase]);',
    '',
    '  const handleVideoEnd = () => {',
    '    setVideoPhase(false);',
    '  };',
    '',
    '  return (',
    '    <section ref={ref} id="top" className="relative min-h-[100svh] overflow-hidden bg-background">',
    '      {/* ── Video intro phase ── */}',
    '      <AnimatePresence>',
    '        {videoPhase && (',
    '           <motion.div',
    '              initial={{ opacity: 1 }}',
    '              exit={{ opacity: 0 }}',
    '              transition={{ duration: 1.5, ease: "easeInOut" }}',
    '              className="absolute inset-0 z-30 bg-black"',
    '           >',
    '              <video ',
    '                src={getAssetUrl("/Hero_BG_Video.mp4")}',
    '                autoPlay ',
    '                muted ',
    '                playsInline',
    '                onEnded={handleVideoEnd}',
    '                className="absolute inset-0 h-full w-full object-cover"',
    '              />',
    '              ',
    '              {/* Dark scrim for text readability */}',
    '              <div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/45 to-transparent" />',
    '              <div className="absolute inset-x-0 bottom-0 h-48 bg-gradient-to-t from-black/80 to-transparent" />',
    '',
    '              {/* Text overlay & CTAs */}',
    '              <div className="absolute inset-0 z-40 flex items-center">',
    '                <div className="mx-auto w-full max-w-7xl px-6">',
    '                  <motion.div',
    '                    initial={{ opacity: 0, y: 12 }}',
    '                    animate={{ opacity: 1, y: 0 }}',
    '                    transition={{ delay: 0.3, duration: 0.8 }}',
    '                    className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-1.5 text-[11px] font-semibold uppercase tracking-[0.25em] text-white/90 backdrop-blur-sm"',
    '                  >',
    '                    <span className="relative flex h-2 w-2">',
    '                      <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-red-400 opacity-75" />',
    '                      <span className="relative inline-flex h-2 w-2 rounded-full bg-red-500" />',
    '                    </span>',
    '                    Engineering Digital Excellence',
    '                  </motion.div>',
    '',
    '                  <motion.h1',
    '                    initial={{ opacity: 0, y: 20 }}',
    '                    animate={{ opacity: 1, y: 0 }}',
    '                    transition={{ delay: 0.6, duration: 0.9, ease: [0.22, 1, 0.36, 1] }}',
    '                    className="mt-7 max-w-3xl text-4xl font-bold leading-[1.05] tracking-tight text-white sm:text-5xl lg:text-6xl xl:text-7xl"',
    '                  >',
    '                    Built on Legacy.{" "}',
    '                    <span className="bg-gradient-to-r from-white via-white/90 to-red-400 bg-clip-text text-transparent">',
    '                      Driven by Innovation.',
    '                    </span>',
    '                  </motion.h1>',
    '',
    '                  <motion.p',
    '                    initial={{ opacity: 0, y: 16 }}',
    '                    animate={{ opacity: 1, y: 0 }}',
    '                    transition={{ delay: 0.9, duration: 0.8 }}',
    '                    className="mt-6 max-w-xl text-base leading-relaxed text-white/75 md:text-lg"',
    '                  >',
    '                    From the Gainwell Group — powering mining, manufacturing, and enterprise transformation with SAP, Zoho, AI, and custom-built digital platforms.',
    '                  </motion.p>',
    '',
    '                  <motion.div',
    '                    initial={{ opacity: 0, y: 16 }}',
    '                    animate={{ opacity: 1, y: 0 }}',
    '                    transition={{ delay: 1.2, duration: 0.7 }}',
    '                    className="mt-9 flex flex-wrap items-center gap-4"',
    '                  >',
    '                    <a',
    '                      href="#contact"',
    '                      className="group inline-flex items-center gap-2.5 rounded-full bg-gradient-to-r from-red-600 to-red-500 px-7 py-4 text-sm font-semibold text-white shadow-lg shadow-red-600/25 transition-all hover:shadow-red-600/40 hover:scale-105"',
    '                    >',
    '                      Start Your Journey',
    '                      <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />',
    '                    </a>',
    '                    <Link',
    '                      to="/services"',
    '                      className="group inline-flex items-center gap-2.5 rounded-full border border-white/20 bg-white/10 px-7 py-4 text-sm font-medium text-white backdrop-blur-sm transition-all hover:bg-white/20"',
    '                    >',
    '                      <span className="grid h-6 w-6 place-items-center rounded-full border border-white/25 transition-transform group-hover:scale-110">',
    '                        <Layers className="h-3 w-3 text-white/80" />',
    '                      </span>',
    '                      Explore Services',
    '                    </Link>',
    '                  </motion.div>',
    '                </div>',
    '              </div>',
    '',
    '              {/* Skip button */}',
    '              <button',
    '                onClick={handleVideoEnd}',
    '                className="absolute bottom-8 right-8 z-50 rounded-full border border-white/20 bg-black/40 px-5 py-2.5 text-xs font-semibold uppercase tracking-widest text-white/80 backdrop-blur-md transition-all hover:bg-black/60 hover:text-white"',
    '              >',
    '                Skip <ArrowRight className="ml-1.5 inline-block h-3 w-3" />',
    '              </button>',
    '           </motion.div>',
    '        )}',
    '      </AnimatePresence>',
    '',
    '      <div className="pointer-events-none absolute inset-0 bg-hero" />',
    '      <div className="pointer-events-none absolute inset-0 grid-lines opacity-[0.08]" />',
    '',
    '      <motion.div',
    '        style={{ y: heroY, opacity: heroOpacity }}',
    '        className="relative z-10 mx-auto flex min-h-[100svh] w-full items-center justify-center px-4 sm:px-6 pt-24 pb-12"',
    '      >',
    '        <div className="relative w-full max-w-7xl aspect-video sm:rounded-3xl overflow-hidden shadow-2xl border border-white/10 bg-white/5 backdrop-blur-3xl flex items-center justify-center">',
    '          ',
    '          <AnimatePresence mode="wait">',
    '             <motion.img ',
    '                key={index}',
    '                src={getAssetUrl(HOME_BANNERS[index])}',
    '                alt="Acceleron Solutions Services"',
    '                initial={{ opacity: 0 }}',
    '                animate={{ opacity: 1 }}',
    '                exit={{ opacity: 0 }}',
    '                transition={{ duration: 1.2, ease: "easeInOut" }}',
    '                className="absolute inset-0 h-full w-full object-contain drop-shadow-2xl"',
    '             />',
    '          </AnimatePresence>',
    '',
    '          <div className="absolute bottom-6 left-1/2 -translate-x-1/2 flex items-center gap-3 z-20">',
    '             {HOME_BANNERS.map((_, i) => (',
    '                <button',
    '                  key={i}',
    '                  onClick={() => setIndex(i)}',
    '                  className={`h-2 rounded-full transition-all shadow-sm ${i === index ? "w-10 bg-brand-red" : "w-3 bg-foreground/30 hover:bg-foreground/50"}`}',
    '                />',
    '             ))}',
    '          </div>',
    '        </div>',
    '      </motion.div>',
    '    </section>',
    '  );',
    '}',
    '',
    '/* ═══════════════════ ABOUT TEASER ═══════════════════ */',
    '',
    'function AboutTeaser() {',
    '  return (',
    '    <section className="relative overflow-hidden bg-background py-24 border-b border-border/50">',
    '      <div className="absolute inset-0 grid-lines opacity-[0.04]" />',
    '      <div className="mx-auto max-w-7xl px-6 relative z-10">',
    '        <div className="grid lg:grid-cols-12 gap-12 lg:gap-16 items-center">',
    '          <div className="lg:col-span-7 space-y-6">',
    '            <Reveal>',
    '              <div className="text-xs uppercase tracking-[0.4em] text-brand-red font-bold">About Acceleron Solutions</div>',
    '            </Reveal>',
    '            <Reveal delay={0.1}>',
    '              <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold text-foreground leading-[1.1]">',
    '                Empowering Enterprises with <span className="text-gradient">Digital Innovation</span>',
    '              </h2>',
    '            </Reveal>',
    '            <Reveal delay={0.2}>',
    '              <p className="text-muted-foreground text-base sm:text-lg leading-relaxed">',
    '                As the technology arm of the Gainwell Group, Acceleron Solutions delivers bespoke SAP consulting, full-stack Zoho business automation, predictive AI systems, and custom enterprise software built for scale.',
    '              </p>',
    '            </Reveal>',
    '            <Reveal delay={0.3}>',
    '              <div className="grid grid-cols-3 gap-4 pt-2 pb-2">',
    '                <div className="rounded-2xl border border-border/60 bg-muted/20 p-4">',
    '                  <div className="text-xl sm:text-2xl font-black text-brand-red">Kolkata & Delhi</div>',
    '                  <div className="text-xs text-muted-foreground mt-1 font-medium">Delivery Hubs</div>',
    '                </div>',
    '                <div className="rounded-2xl border border-border/60 bg-muted/20 p-4">',
    '                  <div className="text-xl sm:text-2xl font-black text-brand-red">Full-Stack</div>',
    '                  <div className="text-xs text-muted-foreground mt-1 font-medium">Enterprise Tech</div>',
    '                </div>',
    '                <div className="rounded-2xl border border-border/60 bg-muted/20 p-4">',
    '                  <div className="text-xl sm:text-2xl font-black text-brand-red">100%</div>',
    '                  <div className="text-xs text-muted-foreground mt-1 font-medium">Outcome Driven</div>',
    '                </div>',
    '              </div>',
    '            </Reveal>',
    '            <Reveal delay={0.4}>',
    '              <div className="pt-2">',
    '                <Link',
    '                  to="/about"',
    '                  className="group inline-flex items-center gap-2.5 rounded-full bg-brand-gradient px-8 py-4 text-sm font-semibold text-white shadow-glow transition-all hover:scale-105 hover:shadow-red-glow"',
    '                >',
    '                  Know More',
    '                  <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />',
    '                </Link>',
    '              </div>',
    '            </Reveal>',
    '          </div>',
    '',
    '          <div className="lg:col-span-5">',
    '            <Reveal delay={0.2}>',
    '              <div className="relative rounded-3xl overflow-hidden border border-border/60 bg-muted/20 shadow-glow p-2">',
    '                <img',
    '                  src={getAssetUrl("/Inaguration Photo.JPG")}',
    '                  alt="Acceleron Solutions"',
    '                  loading="lazy"',
    '                  decoding="async"',
    '                  className="w-full h-[340px] sm:h-[400px] object-cover rounded-2xl"',
    '                />',
    '              </div>',
    '            </Reveal>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
    ''
  ];

  lines.splice(heroLineIdx, storyLineIdx - heroLineIdx, ...replacementLines);
}

// 3. Update Home() to replace EcosystemMarquee with AboutTeaser, and add OurValuesSection
let fileText = lines.join('\n');
fileText = fileText.replace('<EcosystemMarquee />', '<AboutTeaser />');
if (!fileText.includes('<OurValuesSection />')) {
  fileText = fileText.replace('<WhyChooseUs />', '<WhyChooseUs />\n        <OurValuesSection />');
}

// 4. Update Delivery centers in Contact section of index.tsx
const oldLocations = `                    {[
                      "Kolkata, India",
                      "Delhi NCR, India",
                      "Bangalore, India",
                      "West Virginia, USA",
                      "NSW, Australia",
                      "Singapore"
                    ]`;

const newLocations = `                    {[
                      "Kolkata, India",
                      "Delhi NCR, India",
                    ]`;

fileText = fileText.replace(oldLocations, newLocations);
fileText = fileText.replace('Global Delivery Centers', 'Delivery Centers');

fs.writeFileSync(filePath, fileText, 'utf8');
console.log('Successfully updated index.tsx, total lines now:', fileText.split('\n').length);
